<?php
/**
 *author:yyx
 *create_time:2017/9/19 13:22
 *description:
 */
namespace backend\modules\calendar;

use yii\base\Module;

/**
 * 日历模块
 * Class CalendarModule
 * @package backend\modules\calendar
 */
class CalendarModule extends Module
{
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'backend\modules\calendar\controllers';

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}